import streamlit as st

# --------------------------------------------------
# AYARLAR
# --------------------------------------------------

NOTEBOOKLM_URL = (
    "https://notebooklm.google.com/notebook/"
    "65aa8d8b-7e31-4897-9966-941aabf5656d"
)

GA_MEASUREMENT_ID = "G-BC2M5DGTV3"  # <-- BURAYA GA4 ID GELECEK

DEU_BLUE = "#003A8F"
DEU_LIGHT_BLUE = "#E6EEF8"

# --------------------------------------------------
# SAYFA KONFİGÜRASYONU
# --------------------------------------------------

st.set_page_config(
    page_title="DEÜ SBE | Yapay Zeka Asistanı",
    layout="centered"
)

# --------------------------------------------------
# GOOGLE ANALYTICS
# --------------------------------------------------

st.markdown(
    f"""
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id={GA_MEASUREMENT_ID}"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){{dataLayer.push(arguments);}}
gtag('js', new Date());
gtag('config', '{GA_MEASUREMENT_ID}');
</script>
""",
    unsafe_allow_html=True
)

# --------------------------------------------------
# KURUMSAL STİL
# --------------------------------------------------

st.markdown(
    f"""
<style>
body {{
    background-color: {DEU_LIGHT_BLUE};
}}
.stButton>button {{
    background-color: {DEU_BLUE};
    color: white;
    font-size: 16px;
    padding: 10px;
    border-radius: 6px;
}}
.stButton>button:hover {{
    background-color: #002A66;
}}
</style>
""",
    unsafe_allow_html=True
)

# --------------------------------------------------
# DİL SEÇİMİ
# --------------------------------------------------

lang = st.radio(
    "Dil / Language",
    ["Türkçe", "English"],
    horizontal=True
)

# --------------------------------------------------
# LOGO + BAŞLIK
# --------------------------------------------------

st.image("logo_deu.png", width=140)

if lang == "Türkçe":
    st.markdown(
        "<h2>Dokuz Eylül Üniversitesi</h2>"
        "<h4>Sosyal Bilimler Enstitüsü</h4>"
        "<h5>Yapay Zeka Destekli Bilgi Asistanı</h5>",
        unsafe_allow_html=True
    )
else:
    st.markdown(
        "<h2>Dokuz Eylul University</h2>"
        "<h4>Graduate School of Social Sciences</h4>"
        "<h5>AI-Powered Information Assistant</h5>",
        unsafe_allow_html=True
    )

st.divider()

# --------------------------------------------------
# AÇIKLAMA
# --------------------------------------------------

if lang == "Türkçe":
    st.markdown("""
Bu sayfa, **DEÜ Sosyal Bilimler Enstitüsü** tarafından hazırlanan  
**Yapay Zeka Destekli Bilgi Asistanına** erişim sağlamak amacıyla oluşturulmuştur.

Asistan, Enstitü mevzuatı ve ilgili resmî dokümanlar çerçevesinde  
**ön bilgilendirme** sunmaktadır.
""")
else:
    st.markdown("""
This page provides access to the  
**AI-Powered Information Assistant** prepared by  
**DEU Graduate School of Social Sciences**.

The assistant offers **preliminary information** based on official regulations.
""")

# --------------------------------------------------
# UYARI / DISCLAIMER
# --------------------------------------------------

if lang == "Türkçe":
    st.warning("""
**Önemli Bilgilendirme**

Bu asistan tarafından verilen yanıtlar **resmî görüş niteliği taşımaz**.  
Bağlayıcı olan tek kaynak ilgili mevzuat ve Enstitü Yönetim Kurulu kararlarıdır.
""")
else:
    st.warning("""
**Important Notice**

Responses generated by this assistant are **not legally binding**.  
Only official regulations and decisions of the Institute are authoritative.
""")

# --------------------------------------------------
# CHATBOT BUTONU
# --------------------------------------------------

st.link_button(
    "🤖 Yapay Zeka Asistanını Aç" if lang == "Türkçe" else "🤖 Open AI Assistant",
    NOTEBOOKLM_URL,
    use_container_width=True
)

# --------------------------------------------------
# SIK SORULAN SORULAR
# --------------------------------------------------

st.divider()

if lang == "Türkçe":
    st.subheader("📌 Sık Sorulan Sorular")

    with st.expander("Hangi dokümanlar çerçevesinde yanıtlar türetiliyor?"):
        st.write("""
- DEÜ Sosyal Bilimler Enstitüsü Uygulama Esasları  
- Dokuz Eylül Üniversitesi Akademik Danışmanlık Yönergesi  
  (Öğrenci İşleri Daire Başkanlığı)  
- Dokuz Eylül Üniversitesi Lisansüstü Eğitim ve Öğretim Yönetmeliği  
  (Öğrenci İşleri Daire Başkanlığı)  
- Lisansüstü Eğitim ve Öğretim Yönetmeliği  
- Muafiyet ve İntibak Yönergesi  
- Ön Lisans ve Lisans Eğitim-Öğretim ve Sınav Yönetmeliği  
- Yurtdışı Yükseköğrenim Diplomaları ve Denklik Yönetmeliği  
- Yatay Geçiş Yönergesi
""")

    with st.expander("Bu asistan resmî danışmanlık verir mi?"):
        st.write("Hayır. Yalnızca ön bilgilendirme amaçlıdır.")

    with st.expander("Verilerim kaydediliyor mu?"):
        st.write("Bu sayfa yalnızca yönlendirme yapar; sohbet NotebookLM üzerinde gerçekleşir.")

else:
    st.subheader("📌 Frequently Asked Questions")

    with st.expander("Which documents are used as the basis for generating responses?"):
        st.write("""
- DEU Graduate School of Social Sciences – Implementation Guidelines  
- Dokuz Eylul University Academic Advising Directive  
  (Student Affairs Department)  
- Dokuz Eylul University Graduate Education and Training Regulation  
  (Student Affairs Department)  
- Graduate Education and Training Regulation  
- Exemption and Course Adaptation Directive  
- Associate Degree and Undergraduate Education and Examination Regulation  
- Regulation on Foreign Higher Education Diplomas and Equivalency  
- Horizontal Transfer Directive
""")

    with st.expander("Is this an official advisory service?"):
        st.write("No. It is intended for preliminary information only.")

    with st.expander("Is my data stored?"):
        st.write("This page only provides redirection; conversations take place on NotebookLM.")

# --------------------------------------------------
# ALT BİLGİ
# --------------------------------------------------

st.markdown(
    """
<p style="text-align:center; font-size:12px; color:gray;">
© Dokuz Eylül Üniversitesi – Sosyal Bilimler Enstitüsü<br>
Bu sayfa yalnızca bilgilendirme ve yönlendirme amaçlıdır.
</p>
""",
    unsafe_allow_html=True
)
